name: avidemux

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name : Install ffmpeg
      run: |
        sudo apt-get update
        sudo apt-get install ffmpeg


    - name : Install 7Zip
      run: |
        sudo add-apt-repository universe
        sudo apt update
        sudo apt install p7zip-full p7zip-rar

    - name: Download
      run : |
        wget --tries=20 -O file.mkv "http://indexof.ir/redirect/809eRJ"
        
    - name : Compress
      run : |
        ffmpeg -i file.mkv -vcodec libx265 -crf 28 output1.mp4
        7z a -t7z -m0=lzma -mx=9 -mfb=64 -md=32m -ms=on archive1.7z output1.mp4
        ls -la

    - name : Upload
      uses: actions/upload-artifact@v2
      with:
        path: archive1.7z
