name: avidemux

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name : Install ffmpeg
      run: |
        sudo apt-get update
        sudo apt-get install ffmpeg


    - name : Install 7Zip
      run: |
        sudo add-apt-repository universe
        sudo apt update
        sudo apt install p7zip-full p7zip-rar

    - name : Install Axel
      run: |
        sudo apt update
        sudo apt-get install axel

    - name: Download
      run : |
        axel -n 128 -o file.mkv "http://dl1.tmsv.xyz/94/94/series/Silicon.Valley/s1/Silicon.Valley.S01E04.480p.WEB-DL.Tehmovies.me.mkv"
        
    - name : Compress
      run : |
        ffmpeg -i file.mkv -vcodec libx265 -crf 28 output.mp4
        7z a -t7z -m0=lzma -mx=9 -mfb=64 -md=16m -ms=on archive.7z output.mp4
        ls -la

    - name : Upload
      uses: actions/upload-artifact@v2
      with:
        name: original
        path: file.mkv

    - name : Upload
      uses: actions/upload-artifact@v2
      with:
        name: encoded
        path: output.mp4

    - name : Upload
      uses: actions/upload-artifact@v2
      with:
        name: 7z
        path: archive.7z
