name: avidemux

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name : Install ffmpeg
      run: |
        curl -v -L -u octocat:${{ secrets.GITHUB_TOKEN }} -o cut.zip "https://api.github.com/repos/omar-havef/tt/actions/artifacts/12003943/zip"
        ls -la

    - name : Fix
      run: |
        split -b 1289805700 -d -a 3 cut.zip cut_part
        ls -la
        
    - name : Upload
      uses: actions/upload-artifact@v2
      with:
        path: cut_part001
