name: avidemux

on:
  push:
    branches: [master]

jobs:
  prepare:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name : Install ffmpeg
      run: |
        sudo apt-get update
        sudo apt-get install ffmpeg
        
    - name : Install Axel
      run: |
        sudo apt update
        sudo apt-get install axel
        
    - name: Download
      run : |
        wget -O Sherlock.Holmes.2009_.mp4 "https://de4.seedr.cc/ff_get/739513780/Sherlock.Holms.2009.1080p.BrRip.x264.YIFY.mp4?st=hEZUkDbqyZZQgDbjlBzCPw&e=1599479786"

    - name : Split
      run : |
        ffmpeg -i Sherlock.Holmes.2009_.mp4 -f segment -segment_time 2100 -c copy -reset_timestamps 1 Sherlock.Holmes.2009.%01d.mp4
        
    - run: ls -la
      if: always()
        
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: Sherlock.Holmes.2009.YIFY.1
        path: Sherlock.Holmes.2009.1.mp4

    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: Sherlock.Holmes.2009.YIFY.2
        path: Sherlock.Holmes.2009.2.mp4
        
        
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: Sherlock.Holmes.2009.YIFY.3
        path: Sherlock.Holmes.2009.3.mp4

    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: Sherlock.Holmes.2009.YIFY.4
        path: Sherlock.Holmes.2009.4.mp4
        
        
        
  part_1:
    runs-on: ububtu-20.04
    needs: [prepare]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: Sherlock.Holmes.2009.YIFY.1
        
      - run: |
          ffmpeg -i Sherlock.Holmes.2009.1.mp4 -vcodec libx265 -crf 28 Sherlock.Holmes.2009.1_.mp4

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Sherlock.Holmes.2009.YIFY.1_
          path: Sherlock.Holmes.2009.1_.mp4

        
        
        
  part_2:
    runs-on: ububtu-20.04
    needs: [prepare]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: Sherlock.Holmes.2009.YIFY.2
        
      - run: |
          ffmpeg -i Sherlock.Holmes.2009.2.mp4 -vcodec libx265 -crf 28 Sherlock.Holmes.2009.2_.mp4

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Sherlock.Holmes.2009.YIFY.2_
          path: Sherlock.Holmes.2009.2_.mp4
        
        
        
        
  part_3:
    runs-on: ububtu-20.04
    needs: [prepare]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: Sherlock.Holmes.2009.YIFY.3
        
      - run: |
          ffmpeg -i Sherlock.Holmes.2009.3.mp4 -vcodec libx265 -crf 28 Sherlock.Holmes.2009.3_.mp4

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Sherlock.Holmes.2009.YIFY.3_
          path: Sherlock.Holmes.2009.3_.mp4
        
        
        
        
        
  part_4:
    runs-on: ububtu-20.04
    needs: [prepare]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: Sherlock.Holmes.2009.YIFY.4
        
      - run: |
          ffmpeg -i Sherlock.Holmes.2009.4.mp4 -vcodec libx265 -crf 28 Sherlock.Holmes.2009.4_.mp4

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Sherlock.Holmes.2009.YIFY.4_
          path: Sherlock.Holmes.2009.4_.mp4
        
        
        
        
  combine:
    runs-on: ubuntu-20.04
    needs: [prepare , part_1 , part_2 , part_3 , part_4]
    steps:
      - uses:  actions/download-artifact@v2
        with:
          name: Sherlock.Holmes.2009.YIFY.1_
        
      - uses:  actions/download-artifact@v2
        with:
          name: Sherlock.Holmes.2009.YIFY.2_
        
      - uses:  actions/download-artifact@v2
        with:
          name: Sherlock.Holmes.2009.YIFY.3_
      
      - uses:  actions/download-artifact@v2
        with:
          name: Sherlock.Holmes.2009.YIFY.4_
          
      - run : |
          for f in ./*.mp4; do echo "file '$f'" >> mylist.txt; done
          ffmpeg -f concat -safe 0 -i mylist.txt -c copy Sherlock.Holmes.2009.mp4
          
          
      - uses: actions/upload-artifact@v2
        with:
          name: Sherlock.Holmes.2009
          path: Sherlock.Holmes.2009.mp4
        
        
          
