name: avidemux

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download Artifact
      run: |
        curl -v -L -u octocat:${{ secrets.GITHUB_TOKEN }} -o  artifact.zip "https://api.github.com/repos/omar-havef/tt/actions/artifacts/12156010/zip"
        ls -la
        
    - name : Fix
      run: |
        split -b 60981240 -d -a 3 artifact.zip cut_part
        rm cut_part000
        ls -la
        cat cut_part* > cut_all
        ls -la
        
    - name : Upload
      uses: actions/upload-artifact@v2
      with:
        name: 7
        path: cut_all
