name: avidemux

on:
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name : Install ffmpeg
      run: |
        sudo apt-get update
        sudo apt-get install ffmpeg
        
    - name : Install Axel
      run: |
        sudo apt update
        sudo apt-get install axel
        
    - name: Download
      run : |
        wget -O Sherlock.Holmes.A.Game.Of.Shadows.2011.1080p.BrRip.x264.YIFY_.mp4 "https://de4.seedr.cc/ff_get/739513902/Sherlock.Holmes.A.Game.Of.Shadows.2011.1080p.BrRip.x264.YIFY.mp4?st=2jusT2wDz7UiUPmTTLG8Cg&e=1599479870"

    - name : Compress
      run : |
        ffmpeg -i Sherlock.Holmes.A.Game.Of.Shadows.2011.1080p.BrRip.x264.YIFY_.mp4 -vcodec libx265 -crf 28 Sherlock.Holmes.A.Game.Of.Shadows.2011.1080p.BrRip.x264.YIFY.mp4
        
    - run: ls -la
      if: always()
        
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: Sherlock.Holmes.A.Game.Of.Shadows.2011.1080p.BrRip.x264.YIFY
        path: Sherlock.Holmes.A.Game.Of.Shadows.2011.1080p.BrRip.x264.YIFY.mp4

