name: avidemux

on:
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name : Install ffmpeg
      run: |
        sudo apt-get update
        sudo apt-get install ffmpeg
        
    - name : Install Axel
      run: |
        sudo apt update
        sudo apt-get install axel
        
    - name: Download
      run : |
        axel -n 16 -o Black.Mirror.S04E01.mkv "https://fr7.seedr.cc/ff_get/718012967/Black.Mirror.S04E01.BDRip.x264-HAGGiS.mkv?st=pDxgR1Na9tV-iwKIFA8QRA&e=1596585531"
        axel -n 16 -o Black.Mirror.S04E02.mkv "https://fr7.seedr.cc/ff_get/718012968/Black.Mirror.S04E02.BDRip.x264-HAGGiS.mkv?st=tnjIvVRkHaWMXBlaqmxzLw&e=1596585584"
        axel -n 16 -o Black.Mirror.S04E04.mkv "https://fr7.seedr.cc/ff_get/718012970/Black.Mirror.S04E04.BDRip.x264-HAGGiS.mkv?st=cYmj7HVpCq53VBdR8NsTMw&e=1596585605"
        
    - name : Compress
      run : |
        ffmpeg -i Black.Mirror.S04E01.mkv -vcodec libx265 -crf 28 Black.Mirror.S04E01.mp4
        ffmpeg -i Black.Mirror.S04E02.mkv -vcodec libx265 -crf 28 Black.Mirror.S04E02.mp4
        ffmpeg -i Black.Mirror.S04E04.mkv -vcodec libx265 -crf 28 Black.Mirror.S04E04.mp4
        
    - run: ls -la
        
    - uses: actions/upload-artifact@v2
      with:
        name: Black.Mirror.S04E01
        path: Black.Mirror.S04E01.mp4
      
    - uses: actions/upload-artifact@v2
      with:
        name: Black.Mirror.S04E02
        path: Black.Mirror.S04E02.mp4
      
      
    - uses: actions/upload-artifact@v2
      with:
        name: Black.Mirror.S04E04
        path: Black.Mirror.S04E04.mp4
      
