name: selenium

on:
  push:
    branches: [selenium]

jobs:
  download:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name : Install Unrar and7zip
      run: |
        sudo apt-get update
        sudo apt-get install unrar
        sudo apt-get install p7zip-full p7zip-rar
        
    - name: Install Selenium
      run: |
        pip install selenium
        pip3 install selenium
        sudo pip install selenium
        sudo pip3 install selenium
      
    - name : Download
      run: |
        python3 sel.py
        sha1sum WinPE10_8_Sergei_Strelec_x86_x64_2020.09.21_English.rar
        echo "______________________________________________________"
        
    - name : Extract
      continue-on-error: true
      run: |
        unrar x WinPE10_8_Sergei_Strelec_x86_x64_2020.09.21_English.rar -p"strelec"
        echo "ISO Sum"
        md5sum WinPE10_8_Sergei_Strelec_x86_x64_2020.09.21_English.iso
        cat WinPE10_8_Sergei_Strelec_x86_x64_2020.09.21_English.iso.md5
        echo "_______________________________________________________"
        mkdir iso
        cd iso
        7z x ../WinPE10_8_Sergei_Strelec_x86_x64_2020.09.21_English.iso
        
        
    - continue-on-error: true
      if: always()
      run : ls -lRh
      
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: Sergei_Strelec
        path: WinPE10_8_Sergei_Strelec_x86_x64_2020.09.21_English.iso
