name: avidemux

on:
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name : Install ffmpeg
      run: |
        sudo apt-get update
        sudo apt-get install ffmpeg
        
    - name : Install Axel
      run: |
        sudo apt update
        sudo apt-get install axel
        
    - name: Download
      run : |
        wget-O Black.Mirror.S05E01.mp4 "https://fr11.seedr.cc/ff_get/718012854/Black.Mirror.S05E01.WEBRip.x264-ION10.mp4?st=g30W7FgE1oqs_nEyTAZjSw&e=1596585999"
        wget-O Black.Mirror.S05E02.mp4 "https://fr11.seedr.cc/ff_get/718012855/Black.Mirror.S05E02.WEBRip.x264-ION10.mp4?st=vZm36m4OLU3qoZpjHh-mgw&e=1596586095"
        wget-O Black.Mirror.S05E03.mp4 "https://fr11.seedr.cc/ff_get/718012856/Black.Mirror.S05E03.WEBRip.x264-ION10.mp4?st=4Vrb8hiEKqxGSuVusCslaA&e=1596586117"
        
    - name : Compress
      run : |
        ffmpeg -i Black.Mirror.S05E01.mp4 -vcodec libx265 -crf 28 Black.Mirror.S05E01.mp4
        ffmpeg -i Black.Mirror.S05E02.mp4 -vcodec libx265 -crf 28 Black.Mirror.S05E02.mp4
        ffmpeg -i Black.Mirror.S05E03.mp4 -vcodec libx265 -crf 28 Black.Mirror.S05E03.mp4
        
    - run: ls -la
        
    - uses: actions/upload-artifact@v2
      with:
        name: Black.Mirror.S05E01
        path: Black.Mirror.S05E01.mp4
      
    - uses: actions/upload-artifact@v2
      with:
        name: Black.Mirror.S05E02
        path: Black.Mirror.S05E02.mp4
      
      
    - uses: actions/upload-artifact@v2
      with:
        name: Black.Mirror.S05E03
        path: Black.Mirror.S05E03.mp4
      
