name: avidemux

on:
  push:
    branches: [programs]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name : Install 7Zip
      run: |
        sudo add-apt-repository universe
        sudo apt update
        sudo apt install p7zip-full p7zip-rar
        
    - name : Install Axel
      run: |
        sudo apt update
        sudo apt-get install axel
        
    - name: Download
      run : |
        axel -n 8 -o AdobePhotoshop21-mul_x64.zip "https://ccmdls.adobe.com/AdobeESD/PHSP/21.0/win64/99c00910-95d7-4e11-9548-bbbe50361846/AdobePhotoshop21-mul_x64.zip?token=exp=1599014708~hmac=5afd584e3fc806b686b8121a506de69294aca24cb30a11fe04aad53b80bac368"
        axel -n 8 -o AdobeIllustrator24_HD_win64.zip "https://ccmdls.adobe.com/AdobeESD/ILST/24.0/win64/56da4199-7e85-47ac-9805-eb92bb19750f/AdobeIllustrator24_HD_win64.zip?token=exp=1599014753~hmac=5338c9e0dfcf8dc46dd972ae22628d38fecbfd05d5a41dbb68e1f17c259309c4"
        axel -n 8 -o AdobeAudition13All.zip "https://ccmdls.adobe.com/AdobeESD/AUDT/13.0/win64/e31ce5ca-53c7-4b9f-a31c-a15c7dbb8e1a/AdobeAudition13All.zip?token=exp=1599014790~hmac=2896582d77df85746b836a02ed5e7acb026a8d84f2d6494577e120b0c14250db"

    - run: |
        ls -lah
        ls -la
        
    - uses: actions/upload-artifact@v2
      with:
        name: Photoshop
        path: AdobePhotoshop21-mul_x64.zip

    - uses: actions/upload-artifact@v2
      with:
        name: Illustrator
        path: AdobeIllustrator24_HD_win64.zip
        
    - uses: actions/upload-artifact@v2
      with:
        name: Audition
        path: AdobeAudition13All.zip
