name: avidemux

on:
  push:
    branches: [master]

jobs:
  prepare:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name : Install ffmpeg
      run: |
        sudo apt-get update
        sudo apt-get install ffmpeg
        
    - name : Install Axel
      run: |
        sudo apt update
        sudo apt-get install axel
        
    - name : Install Youtube-DL
      run: |
        sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
        sudo chmod a+rx /usr/local/bin/youtube-dl
        
    - name : Download Artifact
      run: |
        curl -v -L -u octocat:${{ secrets.GITHUB_TOKEN }} -o  artifact.zip "https://api.github.com/repos/omar-havef/tt/actions/artifacts/16895248/zip"
        unzip artifact.zip
        ls -lh
        
    - name: Download
      run : |
        youtube-dl -R 1000 -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best' 'https://www.youtube.com/watch?v=BfJUE53-NbY'
        youtube-dl -R 1000 -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best' 'https://www.youtube.com/watch?v=Coaf-i4Kzew'

      
    - run : |
        mkdir new
        for i in *.mp4 ; do
            ffmpeg -i "$i" -vcodec libx265 -crf 28 "./new/$i"
            echo "______________________________________________________________________________________________"
            ls -lh ./new
        done
      
    - run: ls -lah
      if: always()
        
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: videos
        path: ./new/*.mp4
        
#     - uses: actions/upload-artifact@v2
#       if: always()
#       with:
#         name: Sherlock.Holmes.A.Game.Of.Shadows.2011.YIFY.1
#         path: Sherlock.Holmes.A.Game.Of.Shadows.2011.1.mp4

#     - uses: actions/upload-artifact@v2
#       if: always()
#       with:
#         name: Sherlock.Holmes.A.Game.Of.Shadows.2011.YIFY.2
#         path: Sherlock.Holmes.A.Game.Of.Shadows.2011.2.mp4
        
        
#     - uses: actions/upload-artifact@v2
#       if: always()
#       with:
#         name: Sherlock.Holmes.A.Game.Of.Shadows.2011.YIFY.3
#         path: Sherlock.Holmes.A.Game.Of.Shadows.2011.3.mp4

        
                
  # part_0:
  #   runs-on: ubuntu-20.04
  #   needs: [prepare]
  #   steps:
  #     - uses: actions/download-artifact@v2
  #       with:
  #         name: Sherlock.Holmes.A.Game.Of.Shadows.2011.YIFY.0
        
  #     - name : Install ffmpeg
  #       run: |
  #         sudo apt-get update
  #         sudo apt-get install ffmpeg
        
  #     - run: |
  #         ffmpeg -i Sherlock.Holmes.A.Game.Of.Shadows.2011.0.mp4 -vcodec libx265 -crf 28 Sherlock.Holmes.A.Game.Of.Shadows.2011.0_.mp4
  #     - uses: actions/upload-artifact@v2
  #       if: always()
  #       with:
  #         name: Sherlock.Holmes.A.Game.Of.Shadows.2011.YIFY.0_
  #         path: Sherlock.Holmes.A.Game.Of.Shadows.2011.0_.mp4
        
        
  # part_1:
  #   runs-on: ubuntu-20.04
  #   needs: [prepare]
  #   steps:
  #     - uses: actions/download-artifact@v2
  #       with:
  #         name: Sherlock.Holmes.A.Game.Of.Shadows.2011.YIFY.1
        
  #     - name : Install ffmpeg
  #       run: |
  #         sudo apt-get update
  #         sudo apt-get install ffmpeg
          
          
  #     - run: |
  #         ffmpeg -i Sherlock.Holmes.A.Game.Of.Shadows.2011.1.mp4 -vcodec libx265 -crf 28 Sherlock.Holmes.A.Game.Of.Shadows.2011.1_.mp4
  #     - uses: actions/upload-artifact@v2
  #       if: always()
  #       with:
  #         name: Sherlock.Holmes.A.Game.Of.Shadows.2011.YIFY.1_
  #         path: Sherlock.Holmes.A.Game.Of.Shadows.2011.1_.mp4

        
        
        
  # part_2:
  #   runs-on: ubuntu-20.04
  #   needs: [prepare]
  #   steps:
  #     - uses: actions/download-artifact@v2
  #       with:
  #         name: Sherlock.Holmes.A.Game.Of.Shadows.2011.YIFY.2
        
        
  #     - name : Install ffmpeg
  #       run: |
  #         sudo apt-get update
  #         sudo apt-get install ffmpeg
          
  #     - run: |
  #         ffmpeg -i Sherlock.Holmes.A.Game.Of.Shadows.2011.2.mp4 -vcodec libx265 -crf 28 Sherlock.Holmes.A.Game.Of.Shadows.2011.2_.mp4
  #     - uses: actions/upload-artifact@v2
  #       if: always()
  #       with:
  #         name: Sherlock.Holmes.A.Game.Of.Shadows.2011.YIFY.2_
  #         path: Sherlock.Holmes.A.Game.Of.Shadows.2011.2_.mp4
        
        
        
        
  # part_3:
  #   runs-on: ubuntu-20.04
  #   needs: [prepare]
  #   steps:
  #     - uses: actions/download-artifact@v2
  #       with:
  #         name: Sherlock.Holmes.A.Game.Of.Shadows.2011.YIFY.3
        
        
  #     - name : Install ffmpeg
  #       run: |
  #         sudo apt-get update
  #         sudo apt-get install ffmpeg
          
          
  #     - run: |
  #         ffmpeg -i Sherlock.Holmes.A.Game.Of.Shadows.2011.3.mp4 -vcodec libx265 -crf 28 Sherlock.Holmes.A.Game.Of.Shadows.2011.3_.mp4
  #     - uses: actions/upload-artifact@v2
  #       if: always()
  #       with:
  #         name: Sherlock.Holmes.A.Game.Of.Shadows.2011.YIFY.3_
  #         path: Sherlock.Holmes.A.Game.Of.Shadows.2011.3_.mp4
        
        
        
  # combine:
  #   runs-on: ubuntu-20.04
  #   needs: [prepare , part_0 , part_1 , part_2 , part_3]
  #   steps:
      
  #     - uses:  actions/download-artifact@v2
  #       with:
  #         name: Sherlock.Holmes.A.Game.Of.Shadows.2011.YIFY.0_
          
  #     - uses:  actions/download-artifact@v2
  #       with:
  #         name: Sherlock.Holmes.A.Game.Of.Shadows.2011.YIFY.1_
        
  #     - uses:  actions/download-artifact@v2
  #       with:
  #         name: Sherlock.Holmes.A.Game.Of.Shadows.2011.YIFY.2_
        
  #     - uses:  actions/download-artifact@v2
  #       with:
  #         name: Sherlock.Holmes.A.Game.Of.Shadows.2011.YIFY.3_

  #     - run : ls -lah
          
  #     - name : Install ffmpeg
  #       run: |
  #         sudo apt-get update
  #         sudo apt-get install ffmpeg
          
          
  #     - run : |
  #         for f in ./*.mp4; do echo "file '$f'" >> mylist.txt; done
  #         ffmpeg -f concat -safe 0 -i mylist.txt -c copy Sherlock.Holmes.A.Game.Of.Shadows.2011.mp4
          
          
  #     - uses: actions/upload-artifact@v2
  #       with:
  #         name: Sherlock.Holmes.A.Game.Of.Shadows.2011
  #         path: Sherlock.Holmes.A.Game.Of.Shadows.2011.mp4
        
  
