name: avidemux

on:
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name : Install ffmpeg
      run: |
        sudo apt-get update
        sudo apt-get install ffmpeg
        
    - name : Install Axel
      run: |
        sudo apt update
        sudo apt-get install axel
        
    - name: Download
      run : |
        wget -O Sherlock.Holms.2009.1080p.BrRip.x264.YIFY_.mp4 "https://de4.seedr.cc/ff_get/739513780/Sherlock.Holms.2009.1080p.BrRip.x264.YIFY.mp4?st=hEZUkDbqyZZQgDbjlBzCPw&e=1599479786"

    - name : Compress
      run : |
        ffmpeg -i Sherlock.Holms.2009.1080p.BrRip.x264.YIFY_.mp4 -vcodec libx265 -crf 28 Sherlock.Holms.2009.1080p.BrRip.x264.YIFY.mp4

    - run: ls -la
      if: always()
        
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: Sherlock.Holms.2009.1080p.BrRip.x264.YIFY
        path: Sherlock.Holms.2009.1080p.BrRip.x264.YIFY.mp4

