name: avidemux

on:
  push:
    branches: [programs]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name : Install 7Zip
      run: |
        sudo add-apt-repository universe
        sudo apt update
        sudo apt install p7zip-full p7zip-rar
        
    - name : Install Axel
      run: |
        sudo apt update
        sudo apt-get install axel
        
    - name: Download
      run : |
        mkdir new
        cd ./new
        wget -O file.zip "https://megaup.net/1yj3z?pt=ZssuG6a9%2B5LHIGxI7tKxhYF%2BtvrjgrYOcYk%2FfFgFI8U%3D"
        7z x file.zip
        
    - name : Compress
      run : |
        7z --help
        cd ./new
        echo "______________________________________________________________"
        7z a -t7z -m0=lzma -mx=9 -mfb=64 -md=16m -ms=on set.7z "FaresCD.Com.Ado.Phot.2020.v21.2.2.289/Set-up.exe"
        7z a -r -t7z -m0=lzma -mx=9 -mfb=64 -md=16m -ms=on photo.7z "FaresCD.Com.Ado.Phot.2020.v21.2.2.289"

    - run: ls -lahR ./new
      if: always()
        
    - uses: actions/upload-artifact@v2
      if: cancelled()
      with:
        path: ./new/set.7z
        
        
        
