name: avidemux

on:
  push:
    branches: [test]

jobs:
  prepare:

      runs-on: ubuntu-20.04

      steps:

    # - name : Install aria2
    #   run: sudo apt install aria2

    # - name : Download
    #   run: |
    #     sudo mkdir /new
    #     sudo cp '[SANS] security SEC, [2011-2020, ENG] [rutracker-5933310].torrent' /new/
    #     cd /new
    #     sudo aria2c --seed-time=0 --select-file=1569-2788 '[SANS] security SEC, [2011-2020, ENG] [rutracker-5933310].torrent'

      - name: Download Artifact
        run: |
          sudo mkdir -p /new/sans
          cd /new/sans
          sudo curl -v -L -u octocat:${{ secrets.GITHUB_TOKEN }} -o  artifact.zip "https://api.github.com/repos/omar-havef/tt/actions/artifacts/17461899/zip"
          sudo unzip artifact.zip
          sudo rm artifact.zip
          ls -lh
          echo "__________________________________________________________"
          
          SAVEIFS=$IFS # Save the File separator to restore it later
          IFS=$(echo -en "\n\b") # New file separator
          secondDir=(`ls`)
          secondDir="${secondDir[1]}"
          sudo rm -r "$secondDir"
          
          IFS=$SAVEIFS
          
          ls -lh


      - name: Group Files
        run: |
          cd /new/sans/
          
          SAVEIFS=$IFS # Save the File separator to restore it later
          IFS=$(echo -en "\n\b") # New file separator
          arr=(`find -type d`)
          dir=`pwd`
          for ((i = 0 ; i < "${#arr[@]}" ; i++)) ; do
              arr[i]="'${dir}${arr[i]:1}/'" # Convert Relative Paths into Absolute Paths, and add quote around path
          done
          set -x
          
          for i in "${arr[@]}" ; do
              eval "cd $i"
              files=(`find . -maxdepth 1 -type f`)
              if [[ ${#files[@]} != 0 ]]; then
                  for j in "${files[@]}" ; do
                      new_name=`echo ${i:1:-1}${j:2} | sed 's/\//_-_/g'`
                      sudo mv "$j" "$new_name"
                  done
              fi
          done
          echo "__________________________________________________________________"
          cd /new/
          sudo find . -type f -exec mv {} . \;
          sudo rm -r ./sans/
          sudo mkdir d1 d2 d3 d4 d5 d6 d7 d8
          dirs=("d1" "d2" "d3" "d4" "d5" "d6" "d7" "d8")
          flag=1
          while [[ "$flag" == 1 ]] ; do
              for i in "${dirs[@]}" ; do
                  files=(`find . -maxdepth 1 -type f`)
                  if [[ "${#files[@]}" == 0 ]] ; then
                      flag=0
                      break
                  fi
                  sudo mv "${files[0]}" "$i"
              done
          done
          IFS=$SAVEIFS
      - run: ls -lRh /new/
        continue-on-error: true
        if: always()
          
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: d1
          path: "/new/d1/*"

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: d2
          path: "/new/d2/*"

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: d3
          path: "/new/d3/*"

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: d4
          path: "/new/d4/*"

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: d5
          path: "/new/d5/*"

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: d6
          path: "/new/d6/*"

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: d7
          path: "/new/d7/*"

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: d8
          path: "/new/d8/*"


  d1:

    needs: [prepare]
    runs-on: ubuntu-20.04
    steps:
      
      - uses: actions/checkout@v2

      - name : Install ffmpeg
        run: sudo apt install ffmpeg
        
      - run: mkdir ./new/
        
      - name : Download
        uses: actions/download-artifact@v2
        with:
          name: d1
          path: ./new/

      - name: Compress
        run : |
          chmod +x ./ffmpeg.sh
          ./ffmpeg.sh
          
      - run: ls -lRh ./new/
        continue-on-error: true
        if: always()
          
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: _d1
          path: "./new/*"


  d2:

    needs: [prepare]
    runs-on: ubuntu-20.04
    steps:
      
      - uses: actions/checkout@v2
        
      - name : Install ffmpeg
        run: sudo apt install ffmpeg
        
      - run: mkdir ./new/
        
      - name : Download
        uses: actions/download-artifact@v2
        with:
          name: d2
          path: ./new/

      - name: Compress
        run : |
          chmod +x ./ffmpeg.sh
          ./ffmpeg.sh
          
      - run: ls -lRh ./new/
        continue-on-error: true
        if: always()
          
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: _d2
          path: "./new/*"


  d3:

    needs: [prepare]
    runs-on: ubuntu-20.04
    steps:
      
      - uses: actions/checkout@v2

      - name : Install ffmpeg
        run: sudo apt install ffmpeg
        
      - run: mkdir ./new/
        
      - name : Download
        uses: actions/download-artifact@v2
        with:
          name: d3
          path: ./new/

      - name: Compress
        run : |
          chmod +x ./ffmpeg.sh
          ./ffmpeg.sh
          
      - run: ls -lRh ./new/
        continue-on-error: true
        if: always()
          
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: _d3
          path: "./new/*"


  d4:

    needs: [prepare]
    runs-on: ubuntu-20.04
    steps:
      
      - uses: actions/checkout@v2
        
      - name : Install ffmpeg
        run: sudo apt install ffmpeg
        
      - run: mkdir ./new/
        
      - name : Download
        uses: actions/download-artifact@v2
        with:
          name: d4
          path: ./new/

      - name: Compress
        run : |
          chmod +x ./ffmpeg.sh
          ./ffmpeg.sh
          
      - run: ls -lRh ./new/
        continue-on-error: true
        if: always()
          
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: _d4
          path: "./new/*"


  d5:

    needs: [prepare]
    runs-on: ubuntu-20.04
    steps:
      
      - uses: actions/checkout@v2

      - name : Install ffmpeg
        run: sudo apt install ffmpeg
        
      - run: mkdir ./new/
        
      - name : Download
        uses: actions/download-artifact@v2
        with:
          name: d5
          path: ./new/

      - name: Compress
        run : |
          chmod +x ./ffmpeg.sh
          ./ffmpeg.sh
          
      - run: ls -lRh ./new/
        continue-on-error: true
        if: always()
          
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: _d5
          path: "./new/*"


  d6:

    needs: [prepare]
    runs-on: ubuntu-20.04
    steps:
      
      - uses: actions/checkout@v2
        
      - name : Install ffmpeg
        run: sudo apt install ffmpeg
        
      - run: mkdir ./new/
        
      - name : Download
        uses: actions/download-artifact@v2
        with:
          name: d6
          path: ./new/

      - name: Compress
        run : |
          chmod +x ./ffmpeg.sh
          ./ffmpeg.sh
          
      - run: ls -lRh ./new/
        continue-on-error: true
        if: always()
          
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: _d6
          path: "./new/*"


  d7:

    needs: [prepare]
    runs-on: ubuntu-20.04
    steps:
      
      - uses: actions/checkout@v2

      - name : Install ffmpeg
        run: sudo apt install ffmpeg
        
      - run: mkdir ./new/
        
      - name : Download
        uses: actions/download-artifact@v2
        continue-on-error: true
        with:
          name: d7
          path: ./new/

      - name: Compress
        run : |
          chmod +x ./ffmpeg.sh
          ./ffmpeg.sh
          
      - run: ls -lRh ./new/
        continue-on-error: true
        if: always()
          
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: _d7
          path: "./new/*"


  d8:

    needs: [prepare]
    runs-on: ubuntu-20.04
    steps:
      
      - uses: actions/checkout@v2

      - name : Install ffmpeg
        run: sudo apt install ffmpeg
        
      - run: mkdir ./new/
        
      - name : Download
        uses: actions/download-artifact@v2
        continue-on-error: true
        with:
          name: d8
          path: ./new/

      - name: Compress
        run : |
          chmod +x ./ffmpeg.sh
          ./ffmpeg.sh
          
      - run: ls -lRh ./new/
        continue-on-error: true
        if: always()
          
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: _d8
          path: "./new/*"


  combine:

    needs: [d1 , d2 , d3 , d4 , d5 , d6 , d7 , d8]
    runs-on: ubuntu-20.04
    steps:

      - run: |
          mkdir ./new/
          sudo mkdir /new/
        
      - name : Download
        uses: actions/download-artifact@v2
        with:
          name: _d1
          path: ./new/

      - run: sudo mv ./new/* /new/

      - name : Download
        uses: actions/download-artifact@v2
        with:
          name: _d2
          path: ./new/

      - run: sudo mv ./new/* /new/

      - name : Download
        uses: actions/download-artifact@v2
        with:
          name: _d3
          path: ./new/

      - run: sudo mv ./new/* /new/

      - name : Download
        uses: actions/download-artifact@v2
        with:
          name: _d4
          path: ./new/

      - run: sudo mv ./new/* /new/

      - name : Download
        uses: actions/download-artifact@v2
        with:
          name: _d5
          path: ./new/

      - run: sudo mv ./new/* /new/

      - name : Download
        uses: actions/download-artifact@v2
        with:
          name: _d6
          path: ./new/

      - run: sudo mv ./new/* /new/

      - name : Download
        uses: actions/download-artifact@v2
        continue-on-error: true
        with:
          name: _d7
          path: ./new/

      - run: sudo mv ./new/* /new/

      - name : Download
        uses: actions/download-artifact@v2
        continue-on-error: true
        with:
          name: _d8
          path: ./new/

      - run: sudo mv ./new/* /new/

      - name: Combine
        run : |
          cd /new
          SAVEIFS=$IFS # Save the File separator to restore it later
          IFS=$(echo -en "\n\b") # New file separator
          arr=(`find -type f`)
          for i in "${arr[@]}" ; do
              fullfilename=`echo ${i:2} | sed 's/_-_/\//g'` # ${i:2} -> Removes './' at the beginning
              dirname=`dirname $fullfilename`
              if [[ ! -d "$dirname" ]]; then
                  sudo mkdir -p "$dirname"
              fi
              sudo mv "$i"  "$fullfilename"
          done
          IFS=$SAVEIFS
      - run: ls -lRh /new/
        continue-on-error: true
        if: always()
          
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: _all
          path: "/new/*"
