name: avidemux

on:
  push:
    branches: [master]

jobs:
  prepare:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name : Install ffmpeg
      run: |
        sudo apt-get update
        sudo apt-get install ffmpeg
        
    # - name : Install Axel
    #   run: |
    #     sudo apt update
    #     sudo apt-get install axel
        
    - name : Install Youtube-DL
      run: |
        sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
        sudo chmod a+rx /usr/local/bin/youtube-dl
        
#     - name : Download Artifact
#       run: |
#         curl -v -L -u octocat:${{ secrets.GITHUB_TOKEN }} -o  artifact.zip "https://api.github.com/repos/omar-havef/tt/actions/artifacts/16895248/zip"
#         unzip artifact.zip
#         ls -lh
        
    - name: Download
      run : |
        youtube-dl -R 1000 -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best' 'https://www.youtube.com/playlist?list=PLped9VG7STA9Foq9mI5dE6IFUsDxdCHKn'
      
#     - run : |
#         mkdir n1
#         mv ./'Ethical Hacking [Arabic] Video 11-wDAJYIMtm1U.mp4' ./n1/
#         mv ./'Ethical Hacking [Arabic] Video 15-2l9XzZoLUEQ.mp4' ./n1/
#         mv ./'Ethical Hacking [Arabic] Video 43-TujVtcopviw.mp4' ./n1/
#         mv ./'Ethical Hacking [Arabic] Video 45-Eepodov6bso.mp4' ./n1/
#         cd ./n1/
#         mkdir new
        
#         for i in *.mp4 ; do
#             ffmpeg -i "$i" -vcodec libx265 -crf 28 "./new/$i"
#             echo "______________________________________________________________________________________________"
#             ls -lh ./new
#         done

#     - run : |
#         mkdir n1 n2 n3 n4 n5 n6 n7 n8 n9
#         ls -lh
#         SAVEIFS=$IFS
#         IFS=$(echo -en "\n\b")
#         mv `find . -maxdepth 1 -not -type d | head -4` ./n1/
#         mv `find . -maxdepth 1 -not -type d | head -3` ./n2/
#         mv `find . -maxdepth 1 -not -type d | head -2` ./n3/
#         mv `find . -maxdepth 1 -not -type d | head -7` ./n4/
#         mv `find . -maxdepth 1 -not -type d | head -8` ./n5/
#         mv `find . -maxdepth 1 -not -type d | head -5` ./n6/
#         mv `find . -maxdepth 1 -not -type d | head -5` ./n7/
#         mv `find . -maxdepth 1 -not -type d | head -5` ./n8/
#         mv `find . -maxdepth 1 -not -type d | head -5` ./n9/
#         IFS=$SAVEIFS
#         echo "______________________________________"
#         ls -lRh
      
    # - run : |
    #     for i in *.mp4 ; do
    #         ffmpeg -i "$i" -vcodec libx265 -crf 28 "./new/$i"
    #         echo "______________________________________________________________________________________________"
    #         ls -lh ./new
    #     done
      
    - run: ls -lRh
      continue-on-error: true
      if: always()
        
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: videos
        path: ./*.mp4
        
#     - uses: actions/upload-artifact@v2
#       if: always()
#       with:
#         name: videos2
#         path: ./n2/*.mp4
                
#     - uses: actions/upload-artifact@v2
#       if: always()
#       with:
#         name: videos3
#         path: ./n3/*.mp4
                
#     - uses: actions/upload-artifact@v2
#       if: always()
#       with:
#         name: videos4
#         path: ./n4/*.mp4
                
#     - uses: actions/upload-artifact@v2
#       if: always()
#       with:
#         name: videos5
#         path: ./n5/*.mp4
                
#     - uses: actions/upload-artifact@v2
#       if: always()
#       with:
#         name: videos6
#         path: ./n6/*.mp4
                
#     - uses: actions/upload-artifact@v2
#       if: always()
#       with:
#         name: videos7
#         path: ./n7/*.mp4
                
#     - uses: actions/upload-artifact@v2
#       if: always()
#       with:
#         name: videos8
#         path: ./n8/*.mp4
                
#     - uses: actions/upload-artifact@v2
#       if: always()
#       with:
#         name: videos9
#         path: ./n9/*.mp4

                
#   part_1:
#     runs-on: ubuntu-20.04
#     needs: [prepare]
#     steps:
#       - uses: actions/download-artifact@v2
#         with:
#           name: videos1
        
#       - name : Install ffmpeg
#         run: |
#           sudo apt-get update
#           sudo apt-get install ffmpeg
        
#       - run : |
#           mkdir new
#           for i in *.mp4 ; do
#               ffmpeg -i "$i" -vcodec libx265 -crf 28 "./new/$i"
#               echo "______________________________________________________________________________________________"
#               ls -lh ./new
#           done
      
#       - uses: actions/upload-artifact@v2
#         if: always()
#         with:
#           name: _videos1
#           path: ./new/*.mp4

                
#   part_2:
#     runs-on: ubuntu-20.04
#     needs: [prepare]
#     steps:
#       - uses: actions/download-artifact@v2
#         with:
#           name: videos2
        
#       - name : Install ffmpeg
#         run: |
#           sudo apt-get update
#           sudo apt-get install ffmpeg
        
#       - run : |
#           mkdir new
#           for i in *.mp4 ; do
#               ffmpeg -i "$i" -vcodec libx265 -crf 28 "./new/$i"
#               echo "______________________________________________________________________________________________"
#               ls -lh ./new
#           done
      
#       - uses: actions/upload-artifact@v2
#         if: always()
#         with:
#           name: _videos2
#           path: ./new/*.mp4


                
#   part_3:
#     runs-on: ubuntu-20.04
#     needs: [prepare]
#     steps:
#       - uses: actions/download-artifact@v2
#         with:
#           name: videos3
        
#       - name : Install ffmpeg
#         run: |
#           sudo apt-get update
#           sudo apt-get install ffmpeg
        
#       - run : |
#           mkdir new
#           for i in *.mp4 ; do
#               ffmpeg -i "$i" -vcodec libx265 -crf 28 "./new/$i"
#               echo "______________________________________________________________________________________________"
#               ls -lh ./new
#           done
      
#       - uses: actions/upload-artifact@v2
#         if: always()
#         with:
#           name: _videos3
#           path: ./new/*.mp4


                
#   part_4:
#     runs-on: ubuntu-20.04
#     needs: [prepare]
#     steps:
#       - uses: actions/download-artifact@v2
#         with:
#           name: videos4
        
#       - name : Install ffmpeg
#         run: |
#           sudo apt-get update
#           sudo apt-get install ffmpeg
        
#       - run : |
#           mkdir new
#           for i in *.mp4 ; do
#               ffmpeg -i "$i" -vcodec libx265 -crf 28 "./new/$i"
#               echo "______________________________________________________________________________________________"
#               ls -lh ./new
#           done
      
#       - uses: actions/upload-artifact@v2
#         if: always()
#         with:
#           name: _videos4
#           path: ./new/*.mp4



                
#   part_5:
#     runs-on: ubuntu-20.04
#     needs: [prepare]
#     steps:
#       - uses: actions/download-artifact@v2
#         with:
#           name: videos5
        
#       - name : Install ffmpeg
#         run: |
#           sudo apt-get update
#           sudo apt-get install ffmpeg
        
#       - run : |
#           mkdir new
#           for i in *.mp4 ; do
#               ffmpeg -i "$i" -vcodec libx265 -crf 28 "./new/$i"
#               echo "______________________________________________________________________________________________"
#               ls -lh ./new
#           done
      
#       - uses: actions/upload-artifact@v2
#         if: always()
#         with:
#           name: _videos5
#           path: ./new/*.mp4



                
#   part_6:
#     runs-on: ubuntu-20.04
#     needs: [prepare]
#     steps:
#       - uses: actions/download-artifact@v2
#         with:
#           name: videos6
        
#       - name : Install ffmpeg
#         run: |
#           sudo apt-get update
#           sudo apt-get install ffmpeg
        
#       - run : |
#           mkdir new
#           for i in *.mp4 ; do
#               ffmpeg -i "$i" -vcodec libx265 -crf 28 "./new/$i"
#               echo "______________________________________________________________________________________________"
#               ls -lh ./new
#           done
      
#       - uses: actions/upload-artifact@v2
#         if: always()
#         with:
#           name: _videos6
#           path: ./new/*.mp4



                
#   part_7:
#     runs-on: ubuntu-20.04
#     needs: [prepare]
#     steps:
#       - uses: actions/download-artifact@v2
#         with:
#           name: videos7
        
#       - name : Install ffmpeg
#         run: |
#           sudo apt-get update
#           sudo apt-get install ffmpeg
        
#       - run : |
#           mkdir new
#           for i in *.mp4 ; do
#               ffmpeg -i "$i" -vcodec libx265 -crf 28 "./new/$i"
#               echo "______________________________________________________________________________________________"
#               ls -lh ./new
#           done
      
#       - uses: actions/upload-artifact@v2
#         if: always()
#         with:
#           name: _videos7
#           path: ./new/*.mp4



                
#   part_8:
#     runs-on: ubuntu-20.04
#     needs: [prepare]
#     steps:
#       - uses: actions/download-artifact@v2
#         with:
#           name: videos8
        
#       - name : Install ffmpeg
#         run: |
#           sudo apt-get update
#           sudo apt-get install ffmpeg
        
#       - run : |
#           mkdir new
#           for i in *.mp4 ; do
#               ffmpeg -i "$i" -vcodec libx265 -crf 28 "./new/$i"
#               echo "______________________________________________________________________________________________"
#               ls -lh ./new
#           done
      
#       - uses: actions/upload-artifact@v2
#         if: always()
#         with:
#           name: _videos8
#           path: ./new/*.mp4



                
#   part_9:
#     runs-on: ubuntu-20.04
#     needs: [prepare]
#     steps:
#       - uses: actions/download-artifact@v2
#         with:
#           name: videos9
        
#       - name : Install ffmpeg
#         run: |
#           sudo apt-get update
#           sudo apt-get install ffmpeg
        
#       - run : |
#           mkdir new
#           for i in *.mp4 ; do
#               ffmpeg -i "$i" -vcodec libx265 -crf 28 "./new/$i"
#               echo "______________________________________________________________________________________________"
#               ls -lh ./new
#           done
      
#       - uses: actions/upload-artifact@v2
#         if: always()
#         with:
#           name: _videos9
#           path: ./new/*.mp4
