name: avidemux

on:
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name : Install ffmpeg
      run: |
        sudo apt-get update
        sudo apt-get install ffmpeg
        
    - name : Install Axel
      run: |
        sudo apt update
        sudo apt-get install axel
        
    - name: Download
      run : |
        wget -O Django.Unchained.2012_.mp4 "https://de1.seedr.cc/ff_get/720051429/Django.Unchained.2012.1080p.BluRay.x264.YIFY.mp4?st=gtWxDy3zVhKgENV3wZKykg&e=1596857155"

    - name : Compress
      run : |
        ffmpeg -i Django.Unchained.2012_.mp4 -vcodec libx265 -crf 20 Django.Unchained.2012.mp4

    - run: ls -la
        
    - uses: actions/upload-artifact@v2
      with:
        name: Django.Unchained.2012
        path: Django.Unchained.2012.mp4

