name: avidemux

on:
  push:
    branches: [torrent]

jobs:
  prepare:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

#     - name : Install ffmpeg
#       run: |
#         sudo apt-get update
#         sudo apt-get install ffmpeg
        
#     - name : Install Axel
#       run: |
#         sudo apt update
#         sudo apt-get install axel
        
#     - name : Install Transmission
#       run: sudo apt install transmission transmission-cli
        
#     - name : Download
#       run: |
#         mkdir new
#         transmission-cli -D -u 0 -w ./new/ '[SANS] security SEC, [2011-2020, ENG] [rutracker-5933310].torrent'
        
#         for i in *.mp4 ; do
#             ffmpeg -i "$i" -vcodec libx265 -crf 28 "./new/$i"
#             echo "______________________________________________________________________________________________"
#             ls -lh ./new
#         done

    - run: |
        df -h
        ls -lRh
      continue-on-error: true
      if: always()
        
#     - uses: actions/upload-artifact@v2
#       if: always()
#       with:
#         name: videos
#         path: ./new/*.mp4


