name: avidemux

on:
  push:
    branches: [programs]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name : Install 7Zip
      run: |
        sudo add-apt-repository universe
        sudo apt update
        sudo apt install p7zip-full p7zip-rar
        
    - name : Install Axel
      run: |
        sudo apt update
        sudo apt-get install axel
        
    - name: Download
      run : |
        mkdir new
        cd ./new
        axel -n 8 -o file.rar "https://www.up4.cc/downf-159747940574961-rar.html"
        7z e file.rar
        
    - name : Compress
      run : |
        7z --help
        echo "______________________________________________________________"
        7z a -t7z -m0=lzma -mx=9 -mfb=64 -md=16m -ms=on archive.7z file.rar
      
    - run: ls -laHR ./new
      if: always()
        
    - uses: actions/upload-artifact@v2
      if: cancelled()
      with:
        name: Django.Unchained.2012
        path: Django.Unchained.2012.mp4

