name: avidemux

on:
  push:
    branches: [test]

jobs:
  SEC401:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    # - name : Install aria2
    #   run: sudo apt install aria2

    # - name : Download
    #   run: |
    #     sudo mkdir /new
    #     sudo cp '[SANS] security SEC, [2011-2020, ENG] [rutracker-5933310].torrent' /new/
    #     cd /new
    #     sudo aria2c --seed-time=0 --select-file=1569-2788 '[SANS] security SEC, [2011-2020, ENG] [rutracker-5933310].torrent'

    - name: Download Artifact
      run: |
        sudo mkdir -p /new/sans
        cd /new/sans
        sudo curl -v -L -u octocat:${{ secrets.GITHUB_TOKEN }} -o  artifact.zip "https://api.github.com/repos/omar-havef/tt/actions/artifacts/17461897/zip"
        sudo unzip artifact.zip
        sudo rm artifact.zip
        ls -lh
        echo "__________________________________________________________"
        
        SAVEIFS=$IFS # Save the File separator to restore it later
        IFS=$(echo -en "\n\b") # New file separator

        secondDir=(`ls`)
        secondDir="${secondDir[1]}"
        sudo rm -r "$secondDir"
        
        IFS=$SAVEIFS
        
        ls -lh


    - name: Compress
      run : |
        cd /new

        SAVEIFS=$IFS # Save the File separator to restore it later
        IFS=$(echo -en "\n\b") # New file separator

        arr=(`find -type d`)
        dir=`pwd`
        IFS=$SAVEIFS

        for ((i = 0 ; i < "${#arr[@]}" ; i++)) ; do
            arr[i]="'${dir}${arr[i]:1}/'"
        done


        for i in "${arr[@]}" ; do

            eval "cd $i"
            echo "Current Folder is $i"

            mp4FilesCount=`ls -1 *.mp4 2>/dev/null | wc -l`
            webmFilesCount=`ls -1 *.webm 2>/dev/null | wc -l`
            if [[ $mp4FilesCount != 0 && $webmFilesCount != 0 ]]; then
                if [[ ! -d "new" ]]; then
                    sudo mkdir "new"
                fi

                for j in *.mp4 ; do
                    sudo ffmpeg -i "$j" -c:v hevc_nvenc -rc constqp -qp 32 -c:a copy "./new/$j"
                    sudo rm "$j"
                    sudo mv "./new/$j" .
                    echo "________________________________________________________________"
                done
                
                for j in *.webm ; do
                    sudo ffmpeg -i "$j" -c:v hevc_nvenc -rc constqp -qp 32 -c:a copy "./new/$j.mp4"
                    sudo rm "$j"
                    sudo mv "./new/$j.mp4" .
                    echo "________________________________________________________________"
                done
                
                sudo rmdir "./new"
            fi

        done


    - run: ls -lRh /new/
      continue-on-error: true
      if: always()
        
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: SEC401
        path: "/new/sans/*"



  # SEC503:

  #   runs-on: ubuntu-20.04

  #   steps:
  #   - uses: actions/checkout@v2

  #   - name : Install aria2
  #     run: sudo apt install aria2

  #   - name : Download
  #     run: |
  #       sudo mkdir /new
  #       sudo cp '[SANS] security SEC, [2011-2020, ENG] [rutracker-5933310].torrent' /new/
  #       cd /new
  #       sudo aria2c --seed-time=0 --select-file=2807-3648 '[SANS] security SEC, [2011-2020, ENG] [rutracker-5933310].torrent'

  #   - run: ls -lRh /new/
  #     continue-on-error: true
  #     if: always()
        
  #   - uses: actions/upload-artifact@v2
  #     if: always()
  #     with:
  #       name: SEC503
  #       path: "/new/sans/*"



  # SEC504:

  #   runs-on: ubuntu-20.04

  #   steps:
  #   - uses: actions/checkout@v2

  #   - name : Install aria2
  #     run: sudo apt install aria2

  #   - name : Download
  #     run: |
  #       sudo mkdir /new
  #       sudo cp '[SANS] security SEC, [2011-2020, ENG] [rutracker-5933310].torrent' /new/
  #       cd /new
  #       sudo aria2c --seed-time=0 --select-file=3650-4549 '[SANS] security SEC, [2011-2020, ENG] [rutracker-5933310].torrent'

  #   - run: ls -lRh /new/
  #     continue-on-error: true
  #     if: always()
        
  #   - uses: actions/upload-artifact@v2
  #     if: always()
  #     with:
  #       name: SEC504
  #       path: "/new/sans/*"



  # SEC505:

  #   runs-on: ubuntu-20.04

  #   steps:
  #   - uses: actions/checkout@v2

  #   - name : Install aria2
  #     run: sudo apt install aria2

  #   - name : Download
  #     run: |
  #       sudo mkdir /new
  #       sudo cp '[SANS] security SEC, [2011-2020, ENG] [rutracker-5933310].torrent' /new/
  #       cd /new
  #       sudo aria2c --seed-time=0 --select-file=4551-4900 '[SANS] security SEC, [2011-2020, ENG] [rutracker-5933310].torrent'

  #   - run: ls -lRh /new/
  #     continue-on-error: true
  #     if: always()
        
  #   - uses: actions/upload-artifact@v2
  #     if: always()
  #     with:
  #       name: SEC505
  #       path: "/new/sans/*"



  # SEC506:

  #   runs-on: ubuntu-20.04

  #   steps:
  #   - uses: actions/checkout@v2

  #   - name : Install aria2
  #     run: sudo apt install aria2

  #   - name : Download
  #     run: |
  #       sudo mkdir /new
  #       sudo cp '[SANS] security SEC, [2011-2020, ENG] [rutracker-5933310].torrent' /new/
  #       cd /new
  #       sudo aria2c --seed-time=0 --select-file=4902-4978 '[SANS] security SEC, [2011-2020, ENG] [rutracker-5933310].torrent'

  #   - run: ls -lRh /new/
  #     continue-on-error: true
  #     if: always()
        
  #   - uses: actions/upload-artifact@v2
  #     if: always()
  #     with:
  #       name: SEC506
  #       path: "/new/sans/*"


  # SEC542:

  #   runs-on: ubuntu-20.04

  #   steps:
  #   - uses: actions/checkout@v2

  #   - name : Install aria2
  #     run: sudo apt install aria2

  #   - name : Download
  #     run: |
  #       sudo mkdir /new
  #       sudo cp '[SANS] security SEC, [2011-2020, ENG] [rutracker-5933310].torrent' /new/
  #       cd /new
  #       sudo aria2c --seed-time=0 --select-file=4989-5037 '[SANS] security SEC, [2011-2020, ENG] [rutracker-5933310].torrent'

  #   - run: ls -lRh /new/
  #     continue-on-error: true
  #     if: always()
        
  #   - uses: actions/upload-artifact@v2
  #     if: always()
  #     with:
  #       name: SEC542
  #       path: "/new/sans/*"



  # SEC560:

  #   runs-on: ubuntu-20.04

  #   steps:
  #   - uses: actions/checkout@v2

  #   - name : Install aria2
  #     run: sudo apt install aria2

  #   - name : Download
  #     run: |
  #       sudo mkdir /new
  #       sudo cp '[SANS] security SEC, [2011-2020, ENG] [rutracker-5933310].torrent' /new/
  #       cd /new
  #       sudo aria2c --seed-time=0 --select-file=5053-5910 '[SANS] security SEC, [2011-2020, ENG] [rutracker-5933310].torrent'

  #   - run: ls -lRh /new/
  #     continue-on-error: true
  #     if: always()
        
  #   - uses: actions/upload-artifact@v2
  #     if: always()
  #     with:
  #       name: SEC560
  #       path: "/new/sans/*"


  # SEC575:

  #   runs-on: ubuntu-20.04

  #   steps:
  #   - uses: actions/checkout@v2

  #   - name : Install aria2
  #     run: sudo apt install aria2

  #   - name : Download
  #     run: |
  #       sudo mkdir /new
  #       sudo cp '[SANS] security SEC, [2011-2020, ENG] [rutracker-5933310].torrent' /new/
  #       cd /new
  #       sudo aria2c --seed-time=0 --select-file=6182-6885 '[SANS] security SEC, [2011-2020, ENG] [rutracker-5933310].torrent'

  #   - run: ls -lRh /new/
  #     continue-on-error: true
  #     if: always()
        
  #   - uses: actions/upload-artifact@v2
  #     if: always()
  #     with:
  #       name: SEC575
  #       path: "/new/sans/*"


  # SEC580:

  #   runs-on: ubuntu-20.04

  #   steps:
  #   - uses: actions/checkout@v2

  #   - name : Install aria2
  #     run: sudo apt install aria2

  #   - name : Download
  #     run: |
  #       sudo mkdir /new
  #       sudo cp '[SANS] security SEC, [2011-2020, ENG] [rutracker-5933310].torrent' /new/
  #       cd /new
  #       sudo aria2c --seed-time=0 --select-file=6894-6899 '[SANS] security SEC, [2011-2020, ENG] [rutracker-5933310].torrent'

  #   - run: ls -lRh /new/
  #     continue-on-error: true
  #     if: always()
        
  #   - uses: actions/upload-artifact@v2
  #     if: always()
  #     with:
  #       name: SEC580
  #       path: "/new/sans/*"


  # SEC617:

  #   runs-on: ubuntu-20.04

  #   steps:
  #   - uses: actions/checkout@v2

  #   - name : Install aria2
  #     run: sudo apt install aria2

  #   - name : Download
  #     run: |
  #       sudo mkdir /new
  #       sudo cp '[SANS] security SEC, [2011-2020, ENG] [rutracker-5933310].torrent' /new/
  #       cd /new
  #       sudo aria2c --seed-time=0 --select-file=6923-6949 '[SANS] security SEC, [2011-2020, ENG] [rutracker-5933310].torrent'

  #   - run: ls -lRh /new/
  #     continue-on-error: true
  #     if: always()
        
  #   - uses: actions/upload-artifact@v2
  #     if: always()
  #     with:
  #       name: SEC617
  #       path: "/new/sans/*"



  # SEC642:

  #   runs-on: ubuntu-20.04

  #   steps:
  #   - uses: actions/checkout@v2

  #   - name : Install aria2
  #     run: sudo apt install aria2

  #   - name : Download
  #     run: |
  #       sudo mkdir /new
  #       sudo cp '[SANS] security SEC, [2011-2020, ENG] [rutracker-5933310].torrent' /new/
  #       cd /new
  #       sudo aria2c --seed-time=0 --select-file=6951-7755 '[SANS] security SEC, [2011-2020, ENG] [rutracker-5933310].torrent'

  #   - run: ls -lRh /new/
  #     continue-on-error: true
  #     if: always()
        
  #   - uses: actions/upload-artifact@v2
  #     if: always()
  #     with:
  #       name: SEC642
  #       path: "/new/sans/*"




  # SEC660:

  #   runs-on: ubuntu-20.04

  #   steps:
  #   - uses: actions/checkout@v2

  #   - name : Install aria2
  #     run: sudo apt install aria2

  #   - name : Download
  #     run: |
  #       sudo mkdir /new
  #       sudo cp '[SANS] security SEC, [2011-2020, ENG] [rutracker-5933310].torrent' /new/
  #       cd /new
  #       sudo aria2c --seed-time=0 --select-file=7757-7796 '[SANS] security SEC, [2011-2020, ENG] [rutracker-5933310].torrent'

  #   - run: ls -lRh /new/
  #     continue-on-error: true
  #     if: always()
        
  #   - uses: actions/upload-artifact@v2
  #     if: always()
  #     with:
  #       name: SEC660
  #       path: "/new/sans/*"
