name: avidemux

on:
  push:
    branches: [torrent]

jobs:
  FOR500:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name : Install aria2
      run: sudo apt install aria2

    - name : Download
      run: |
        sudo mkdir /new
        sudo cp '[SANS] security SEC, [2011-2020, ENG] [rutracker-5933310].torrent' /new/
        cd /new
        sudo aria2c --seed-time=0 --select-file=47-663 '[SANS] security SEC, [2011-2020, ENG] [rutracker-5933310].torrent'

    - run: ls -lRh /new/
      continue-on-error: true
      if: always()
        
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: FOR500
        path: "/new/sans/*"



  FOR508:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name : Install aria2
      run: sudo apt install aria2

    - name : Download
      run: |
        sudo mkdir /new
        sudo cp '[SANS] security SEC, [2011-2020, ENG] [rutracker-5933310].torrent' /new/
        cd /new
        sudo aria2c --seed-time=0 --select-file=663-694 '[SANS] security SEC, [2011-2020, ENG] [rutracker-5933310].torrent'

    - run: ls -lRh /new/
      continue-on-error: true
      if: always()
        
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: FOR508
        path: "/new/sans/*"



  FOR526:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name : Install aria2
      run: sudo apt install aria2

    - name : Download
      run: |
        sudo mkdir /new
        sudo cp '[SANS] security SEC, [2011-2020, ENG] [rutracker-5933310].torrent' /new/
        cd /new
        sudo aria2c --seed-time=0 --select-file=702-1506 '[SANS] security SEC, [2011-2020, ENG] [rutracker-5933310].torrent'

    - run: ls -lRh /new/
      continue-on-error: true
      if: always()
        
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: FOR526
        path: "/new/sans/*"



  FOR585:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name : Install aria2
      run: sudo apt install aria2

    - name : Download
      run: |
        sudo mkdir /new
        sudo cp '[SANS] security SEC, [2011-2020, ENG] [rutracker-5933310].torrent' /new/
        cd /new
        sudo aria2c --seed-time=0 --select-file=1520-1524 '[SANS] security SEC, [2011-2020, ENG] [rutracker-5933310].torrent'

    - run: ls -lRh /new/
      continue-on-error: true
      if: always()
        
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: FOR585
        path: "/new/sans/*"



  FOR610:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name : Install aria2
      run: sudo apt install aria2

    - name : Download
      run: |
        sudo mkdir /new
        sudo cp '[SANS] security SEC, [2011-2020, ENG] [rutracker-5933310].torrent' /new/
        cd /new
        sudo aria2c --seed-time=0 --select-file=1526-1542 '[SANS] security SEC, [2011-2020, ENG] [rutracker-5933310].torrent'

    - run: ls -lRh /new/
      continue-on-error: true
      if: always()
        
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: FOR610
        path: "/new/sans/*"


