name: avidemux

on:
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name : Install ffmpeg
      run: |
        sudo apt-get update
        sudo apt-get install ffmpeg
        
    - name : Install Axel
      run: |
        sudo apt update
        sudo apt-get install axel
        
    - name: Download
      run : |
        wget -O gone.girl_.mp4 "https://de12.seedr.cc/ff_get/720051412/Gone.Girl.2014.1080p.BluRay.x264.YIFY.mp4?st=D6a0lWBXRPZTP_AHwMU0Pg&e=1596857041"

    - name : Compress
      run : |
        ffmpeg -i gone.girl_.mp4 -vcodec libx265 -crf 20 Gone.Girl.mp4

    - run: ls -la
        
    - uses: actions/upload-artifact@v2
      with:
        name: Gone.Girl
        path: Gone.Girl.mp4

