name: avidemux

on:
  push:
    branches: [torrent]

jobs:
  prepare:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

#     - name : Install ffmpeg
#       run: |
#         sudo apt-get update
#         sudo apt-get install ffmpeg
        
#     - name : Install Axel
#       run: |
#         sudo apt update
#         sudo apt-get install axel

    - name : Install Transmission
      run: sudo apt install aria2


    - name : Download
      run: |
        cd /
        sudo mkdir new
        cd new
        sudo wget https://releases.ubuntu.com/20.04/ubuntu-20.04.1-live-server-amd64.iso.torrent
        sudo aria2c -S 'ubuntu-20.04.1-live-server-amd64.iso.torrent'
        sudo aria2c --seed-time=0 --select-file=1 'ubuntu-20.04.1-live-server-amd64.iso.torrent'
        
        
#     - run : |
#         df -h
#         wget https://releases.ubuntu.com/20.04/ubuntu-20.04.1-live-server-amd64.iso.torrent
#         sudo cp 'ubuntu-20.04.1-live-server-amd64.iso.torrent' /
#         cd /
        
#     - name : Install Transmission
#       run: sudo apt install ctorrent


#     - name : Download
#       run: |
#         cd /
#         ls -l
#         sudo mkdir new
#         sudo ctorrent 'ubuntu-20.04.1-live-server-amd64.iso.torrent'
        
#         for i in *.mp4 ; do
#             ffmpeg -i "$i" -vcodec libx265 -crf 28 "./new/$i"
#             echo "______________________________________________________________________________________________"
#             ls -lh ./new
#         done

    - run: ls -lRh /new/
      continue-on-error: true
      if: always()
        
#     - uses: actions/upload-artifact@v2
#       if: always()
#       with:
#         name: videos
#         path: ./new/*.mp4


