name: avidemux

on:
  push:
    branches: [programs]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name : Install 7Zip
      run: |
        sudo add-apt-repository universe
        sudo apt update
        sudo apt install p7zip-full p7zip-rar
        
    - name : Install Axel
      run: |
        sudo apt update
        sudo apt-get install axel
        
    - name: Download
      run : |
        mkdir new
        cd ./new
        axel -n 8 -o file.rar "https://www.up4.cc/downf-159747940574961-rar.html"
        7z x file.rar
        
        axel -n 8 -o ph.zip "https://ccmdls.adobe.com/AdobeESD/PHSP/21.0/win64/99c00910-95d7-4e11-9548-bbbe50361846/AdobePhotoshop21-mul_x64.zip?token=exp=1599014708~hmac=5afd584e3fc806b686b8121a506de69294aca24cb30a11fe04aad53b80bac368"
        7z x ph.zip
        
    - name : Compress
      run : |
        7z --help
        cd ./new
        echo "______________________________________________________________"
        7z a -t7z -m0=lzma -mx=9 -mfb=64 -md=16m -ms=on set.7z "FaresCD.Com.Ado.Phot.2020.v21.2.2.289/Set-up.exe"
        7z a -r -t7z -m0=lzma -mx=9 -mfb=64 -md=16m -ms=on photo.7z "FaresCD.Com.Ado.Phot.2020.v21.2.2.289"
        
    - run: ls -lahR ./new
      if: always()
        
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        path: ./new/set.7z
          
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: Photoshop
        path: ./new/ph.zip
