name: avidemux

on:
  push:
    branches: [full]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install ffmpeg

      - name: Install 7Zip
        run: |
          sudo add-apt-repository universe
          sudo apt update
          sudo apt install p7zip-full p7zip-rar

      - name: Install Axel
        run: |
          sudo apt update
          sudo apt-get install axel

      - name: Download
        run: |
          axel -n 512 -o file01.mkv "http://dl1.tmsv.xyz/94/94/series/Silicon.Valley/s3/Silicon.Valley.S02E01.480p.Tehmovies.me.mkv"
          axel -n 512 -o file02.mkv "http://dl1.tmsv.xyz/94/94/series/Silicon.Valley/s3/Silicon.Valley.S02E02.480p.Tehmovies.me.mkv"
          axel -n 512 -o file03.mkv "http://dl1.tmsv.xyz/94/94/series/Silicon.Valley/s3/Silicon.Valley.S02E03.480p.Tehmovies.me.mkv"
          axel -n 512 -o file04.mkv "http://dl1.tmsv.xyz/94/94/series/Silicon.Valley/s3/Silicon.Valley.S02E04.480p.Tehmovies.me.mkv"
          axel -n 512 -o file05.mkv "http://dl1.tmsv.xyz/94/94/series/Silicon.Valley/s3/Silicon.Valley.S02E05.480p.Tehmovies.me.mkv"
          axel -n 512 -o file06.mkv "http://dl1.tmsv.xyz/94/94/series/Silicon.Valley/s3/Silicon.Valley.S02E06.480p.Tehmovies.me.mkv"
          axel -n 512 -o file07.mkv "http://dl1.tmsv.xyz/94/94/series/Silicon.Valley/s3/Silicon.Valley.S02E07.480p.Tehmovies.me.mkv"
          axel -n 512 -o file08.mkv "http://dl1.tmsv.xyz/94/94/series/Silicon.Valley/s3/Silicon.Valley.S02E08.480p.Tehmovies.me.mkv"
          axel -n 512 -o file09.mkv "http://dl1.tmsv.xyz/94/94/series/Silicon.Valley/s3/Silicon.Valley.S02E09.480p.Tehmovies.me.mkv"
          axel -n 512 -o file10.mkv "http://dl1.tmsv.xyz/94/94/series/Silicon.Valley/s3/Silicon.Valley.S02E10.480p.Tehmovies.me.mkv"
          
          ls -la
          
      - name: Compress
        run: |
          ffmpeg -i file01.mkv -vcodec libx265 -crf 28 S02E01.mp4
          ffmpeg -i file02.mkv -vcodec libx265 -crf 28 S02E02.mp4
          ffmpeg -i file03.mkv -vcodec libx265 -crf 28 S02E03.mp4
          ffmpeg -i file04.mkv -vcodec libx265 -crf 28 S02E04.mp4
          ffmpeg -i file05.mkv -vcodec libx265 -crf 28 S02E05.mp4
          ffmpeg -i file06.mkv -vcodec libx265 -crf 28 S02E06.mp4
          ffmpeg -i file07.mkv -vcodec libx265 -crf 28 S02E07.mp4
          ffmpeg -i file08.mkv -vcodec libx265 -crf 28 S02E08.mp4
          ffmpeg -i file09.mkv -vcodec libx265 -crf 28 S02E09.mp4
          ffmpeg -i file10.mkv -vcodec libx265 -crf 28 S02E10.mp4

      - name: 7-Zip
        run: |
          7z a -t7z -m0=lzma -mx=9 -mfb=64 -md=16m -ms=on lzma_16.7z S02E01.mp4 S02E02.mp4 S02E03.mp4 S02E04.mp4 S02E05.mp4 S02E06.mp4 S02E07.mp4 S02E08.mp4 S02E09.mp4 S02E10.mp4
          7z a -t7z -m0=lzma -mx=9 -mfb=64 -md=32m -ms=on lzma_32.7z S02E01.mp4 S02E02.mp4 S02E03.mp4 S02E04.mp4 S02E05.mp4 S02E06.mp4 S02E07.mp4 S02E08.mp4 S02E09.mp4 S02E10.mp4

          7z a -t7z -m0=lzma2 -mx=9 -mfb=64 -md=16m -ms=on lzma2_16.7z S02E01.mp4 S02E02.mp4 S02E03.mp4 S02E04.mp4 S02E05.mp4 S02E06.mp4 S02E07.mp4 S02E08.mp4 S02E09.mp4 S02E10.mp4
          7z a -t7z -m0=lzma2 -mx=9 -mfb=64 -md=32m -ms=on lzma2_32.7z S02E01.mp4 S02E02.mp4 S02E03.mp4 S02E04.mp4 S02E05.mp4 S02E06.mp4 S02E07.mp4 S02E08.mp4 S02E09.mp4 S02E10.mp4

          ls -la

      - name: Upload S02E01 
        uses: actions/upload-artifact@v2
        with:
          name: S02E01
          path: S02E01.mp4
          
      - name: Upload S02E02 
        uses: actions/upload-artifact@v2
        with:
          name: S02E02
          path: S02E02.mp4
          
      - name: Upload S02E03 
        uses: actions/upload-artifact@v2
        with:
          name: S02E03
          path: S02E03.mp4
          
      - name: Upload S02E04 
        uses: actions/upload-artifact@v2
        with:
          name: S02E04
          path: S02E04.mp4
          
      - name: Upload S02E05 
        uses: actions/upload-artifact@v2
        with:
          name: S02E05
          path: S02E05.mp4
          
      - name: Upload S02E06 
        uses: actions/upload-artifact@v2
        with:
          name: S02E06
          path: S02E06.mp4
          
      - name: Upload S02E07 
        uses: actions/upload-artifact@v2
        with:
          name: S02E07
          path: S02E07.mp4
          
      - name: Upload S02E08 
        uses: actions/upload-artifact@v2
        with:
          name: S02E08
          path: S02E08.mp4
          
      - name: Upload S02E09 
        uses: actions/upload-artifact@v2
        with:
          name: S02E09
          path: S02E09.mp4
          
      - name: Upload S02E10 
        uses: actions/upload-artifact@v2
        with:
          name: S02E10
          path: S02E10.mp4
          
