name: avidemux

on:
  push:
    branches: [full]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install ffmpeg

      - name: Install Axel
        run: |
          sudo apt update
          sudo apt-get install axel

      - name: Download
        run: |
          axel -n 128 -o file01.mkv "http://dl1.tmsv.xyz/94/94/series/Silicon.Valley/s3/silicon.valley.s03e01.480p.Tehmovies.me.mkv"
          axel -n 128 -o file02.mkv "http://dl1.tmsv.xyz/94/94/series/Silicon.Valley/s3/silicon.valley.s03e02.480p.Tehmovies.me.mkv"
          axel -n 128 -o file03.mkv "http://dl1.tmsv.xyz/94/94/series/Silicon.Valley/s3/silicon.valley.s03e03.480p.Tehmovies.me.mkv"
          axel -n 128 -o file04.mkv "http://dl1.tmsv.xyz/94/94/series/Silicon.Valley/s3/silicon.valley.s03e04.480p.Tehmovies.me.mkv"
          axel -n 128 -o file05.mkv "http://dl1.tmsv.xyz/94/94/series/Silicon.Valley/s3/silicon.valley.s03e05.480p.Tehmovies.me.mkv"
          axel -n 128 -o file06.mkv "http://dl1.tmsv.xyz/94/94/series/Silicon.Valley/s3/silicon.valley.s03e06.480p.Tehmovies.me.mkv"
          axel -n 128 -o file07.mkv "http://dl1.tmsv.xyz/94/94/series/Silicon.Valley/s3/silicon.valley.s03e07.480p.Tehmovies.me.mkv"
          axel -n 128 -o file08.mkv "http://dl1.tmsv.xyz/94/94/series/Silicon.Valley/s3/silicon.valley.s03e08.480p.Tehmovies.me.mkv"
          axel -n 128 -o file09.mkv "http://dl1.tmsv.xyz/94/94/series/Silicon.Valley/s3/silicon.valley.s03e09.480p.Tehmovies.me.mkv"
          axel -n 128 -o file10.mkv "http://dl1.tmsv.xyz/94/94/series/Silicon.Valley/s3/silicon.valley.s03e10.proper.480p.Tehmovies.me.mkv"
          
          
      - name: Compress
        run: |
          ffmpeg -i file01.mkv -vcodec libx265 -crf 28 S03E01.mp4
          ffmpeg -i file02.mkv -vcodec libx265 -crf 28 S03E02.mp4
          ffmpeg -i file03.mkv -vcodec libx265 -crf 28 S03E03.mp4
          ffmpeg -i file04.mkv -vcodec libx265 -crf 28 S03E04.mp4
          ffmpeg -i file05.mkv -vcodec libx265 -crf 28 S03E05.mp4
          ffmpeg -i file06.mkv -vcodec libx265 -crf 28 S03E06.mp4
          ffmpeg -i file07.mkv -vcodec libx265 -crf 28 S03E07.mp4
          ffmpeg -i file08.mkv -vcodec libx265 -crf 28 S03E08.mp4
          ffmpeg -i file09.mkv -vcodec libx265 -crf 28 S03E09.mp4
          ffmpeg -i file10.mkv -vcodec libx265 -crf 28 S03E10.mp4

      - name: Upload S03E01 
        uses: actions/upload-artifact@v2
        with:
          name: S03E01
          path: S03E01.mp4
          
      - name: Upload S03E02 
        uses: actions/upload-artifact@v2
        with:
          name: S03E02
          path: S03E02.mp4
          
      - name: Upload S03E03 
        uses: actions/upload-artifact@v2
        with:
          name: S03E03
          path: S03E03.mp4
          
      - name: Upload S03E04 
        uses: actions/upload-artifact@v2
        with:
          name: S03E04
          path: S03E04.mp4
          
      - name: Upload S03E05 
        uses: actions/upload-artifact@v2
        with:
          name: S03E05
          path: S03E05.mp4
          
      - name: Upload S03E06 
        uses: actions/upload-artifact@v2
        with:
          name: S03E06
          path: S03E06.mp4
          
      - name: Upload S03E07 
        uses: actions/upload-artifact@v2
        with:
          name: S03E07
          path: S03E07.mp4
          
      - name: Upload S03E08 
        uses: actions/upload-artifact@v2
        with:
          name: S03E08
          path: S03E08.mp4
          
      - name: Upload S03E09 
        uses: actions/upload-artifact@v2
        with:
          name: S03E09
          path: S03E09.mp4
          
      - name: Upload S03E10 
        uses: actions/upload-artifact@v2
        with:
          name: S03E10
          path: S03E10.mp4
          
